apiVersion: v1
kind: Service
metadata:
  name: app-service-orders
spec:
  selector:
    app: fiap-orders-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30009
  type: NodePort
